### ISSUE TITLE
new-shell prompt messy

### ISSUE THREAD

**Issue by lyqscmy** [TikhonJelvis/dotfiles#1]
I copy your new-shell funtion into my .emacs.

After input buffer name 'irb',it shows as below.

export PS1="^Gmirb^Gm:^Gm\W^Gm>"
mirbm:m\Wm>

**Comment by lyqscmy** [comment]
no �

**Comment by TikhonJelvis** [comment]
I like to have a custom prompt in each shell buffer with the name of that buffer. The characters that don't show up are ANSI escape codes to set the colors. 

Here's the line that does that:

``` elisp
(comint-simple-send (get-buffer-process (current-buffer)) 
                        (concat "export PS1=\"\033[33m" name "\033[0m:\033[35m\\W\033[0m>\""))
```

For some reason, the codes aren't working for you. Either something got messed up when you copied and pasted or your shell does not support these features properly.

If you don't want to modify your prompt at all, just delete that line above. Here's the function without it:

``` elisp
(defun new-shell (name)
  "Opens a new shell buffer with the given name in
asterisks (*name*) in the current directory with and changes the
prompt to name>."
  (interactive "sName: ")
  (pop-to-buffer (concat "*" name "*"))
  (unless (eq major-mode 'shell-mode)
    (shell (current-buffer))
    (sleep-for 0 200)
    (delete-region (point-min) (point-max))))
```

You could also try having a custom prompt but without the color codes to see if it works at all. I personally find having the name of the buffer (`irb` in your case) very useful. Here's a version of the function that sets your prompt but does not use ANSI codes:

``` elisp
(defun new-shell (name)
  "Opens a new shell buffer with the given name in
asterisks (*name*) in the current directory with and changes the
prompt to name>."
  (interactive "sName: ")
  (pop-to-buffer (concat "*" name "*"))
  (unless (eq major-mode 'shell-mode)
    (shell (current-buffer))
    (sleep-for 0 200)
    (delete-region (point-min) (point-max))
    (comint-simple-send (get-buffer-process (current-buffer)) 
                        (concat "export PS1=\"" name "\\W>\""))))
```

Hope that helps!

**Comment by lyqscmy** [comment]
Thanks for your help!I chose the first version.

But why my prompt in emacs doesn't look colorful like in terminal.
![qq 20150819173241](https://cloud.githubusercontent.com/assets/8686356/9353810/eb9632c6-469d-11e5-83ba-6cd8f56a7d44.png)
![qq 20150819173308](https://cloud.githubusercontent.com/assets/8686356/9353811/eb97514c-469d-11e5-831b-e1c675719f1d.png)

And another problem is how to disable the command echoing.At last,do you know how to make C-l behavior like terminal?'erase-buffer' can clean up output. But I want to keep history.

**Comment by TikhonJelvis** [comment]
I'm not sure about the colors. They used to work, but randomly stopped around Emacs 24. I'll look around to see if I can fix them again, but no promises.

I don't have command echoing, so I'm not sure why you do. Try disabling it by setting `comint-process-echoes` to `t` (advice from the [manual](https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Shell-echo.html)).

What do you mean by keeping history? `erase-buffer` should not affect your command history at all, unless I'm misunderstanding.

**Comment by TikhonJelvis** [comment]
Looks like the color issue is a [known bug](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20084) and should be fixed in Emacs 25.1.

**Comment by lyqscmy** [comment]
I mean keeping the output history,not the command history.

**Comment by TikhonJelvis** [comment]
Totally sorry, I completely forgot your last question!

In the terminal, the way C-l is usually implemented is by scrolling the prompt to the top of your screen, and perhaps adding in some blank lines. You can get the first part of this effect by pressing C-l twice in succession. (Presumably, that's where the Emacs key binding comes from.) 

I don't know of any built-in command to pad with extra whitespace, but it shouldn't be difficult to write your own function to do that. I'd give you a quick example, but I'm in my phone; if you still want something like that, feel free to ping me.
